using System;
using System.Collections;
using System.Collections.Generic;
using Meta.XR.MRUtilityKit;
using UnityEngine;
using UnityEngine.AI;
using UnityEngine.Events;

/// <summary>
/// Reusable system to apply components (by default a <see cref="NavMeshObstacle"/> with carving)
/// to the objects generated by Meta's MR Utility Kit <see cref="EffectMesh"/>.
///
/// - Filters by object type through <see cref="targetLabels"/> (tables, walls, couches, etc.).
/// - Works off MRUK events (scene loaded / room updated), no continuous polling.
/// - Keeps a registry of the managed objects so you can act on them later
///   (see <see cref="ManagedObjects"/> and public methods such as <see cref="SetCarving"/>).
/// - Exposes <see cref="onEffectMeshMatched"/> to attach, from the Inspector or from code, any
///   additional script/component to the effect meshes that pass the filter.
///
/// Attach it to the same GameObject that holds the <see cref="EffectMesh"/> component
/// (in the ZombieMR scene: "[BuildingBlock] EffectMesh").
/// </summary>
[RequireComponent(typeof(EffectMesh))]
[DisallowMultipleComponent]
public class EffectMeshComponentApplier : MonoBehaviour
{
    /// <summary>Event invoked for each effect mesh that passes the filter (generated GameObject + source anchor).</summary>
    [Serializable]
    public class EffectMeshMatchedEvent : UnityEvent<GameObject, MRUKAnchor> { }

    [Header("Object Type Filter")]
    [Tooltip("Only EffectMesh objects whose anchor has at least one of these labels will receive the components. " +
             "Select here the types you want to act on (TABLE, WALL_FACE, etc.).")]
    public MRUKAnchor.SceneLabels targetLabels =
        MRUKAnchor.SceneLabels.TABLE |
        MRUKAnchor.SceneLabels.WALL_FACE |
        MRUKAnchor.SceneLabels.INVISIBLE_WALL_FACE |
        MRUKAnchor.SceneLabels.COUCH |
        MRUKAnchor.SceneLabels.STORAGE |
        MRUKAnchor.SceneLabels.BED |
        MRUKAnchor.SceneLabels.SCREEN |
        MRUKAnchor.SceneLabels.OTHER;

    [Header("NavMeshObstacle")]
    [Tooltip("If enabled, adds and configures a NavMeshObstacle on every effect mesh that passes the filter.")]
    public bool addNavMeshObstacle = true;

    [Tooltip("Enables carving: the obstacle cuts a hole in the already baked NavMesh.")]
    public bool carving = true;

    [Tooltip("Carve only when the obstacle is stationary (recommended for static objects like tables and walls).")]
    public bool carveOnlyStationary = true;

    [Tooltip("Obstacle shape. Box is suitable for tables, walls and volumes in general.")]
    public NavMeshObstacleShape shape = NavMeshObstacleShape.Box;

    [Tooltip("Minimum obstacle size along each axis (avoids zero-thickness obstacles, e.g. walls).")]
    public Vector3 minimumSize = new Vector3(0.05f, 0.05f, 0.05f);

    [Tooltip("Thickness used for planar objects (walls) that have no volume.")]
    public float planeThickness = 0.05f;

    public float carvingMoveThreshold = 0.1f;
    public float carvingTimeToStationary = 0.5f;

    [Header("When To Apply")]
    [Tooltip("Apply when the MRUK scene has been loaded.")]
    public bool applyOnSceneLoaded = true;

    [Tooltip("Reapply when a room is created or updated (anchors added/removed at runtime).")]
    public bool reapplyOnRoomUpdated = true;

    [Tooltip("Safety rescan interval (s). 0 = disabled (recommended, events only).")]
    [Min(0f)]
    public float periodicRescanInterval = 0f;

    [Header("Extensibility")]
    [Tooltip("Invoked once for each effect mesh that passes the filter. " +
             "Use it to add other scripts/components without editing this file.")]
    public EffectMeshMatchedEvent onEffectMeshMatched;

    [Header("Debug")]
    public bool logActions;

    private EffectMesh _effectMesh;
    private MRUK _mruk;
    private readonly Dictionary<MRUKAnchor, GameObject> _managed = new();
    private Coroutine _rescanRoutine;
    private Coroutine _initRoutine;
    private Coroutine _deferredApplyRoutine;

    /// <summary>Read-only map anchor -> GameObject of the effect mesh currently managed.</summary>
    public IReadOnlyDictionary<MRUKAnchor, GameObject> ManagedObjects => _managed;

    /// <summary>The source EffectMesh this applier is attached to.</summary>
    public EffectMesh SourceEffectMesh => _effectMesh;

    private void Awake()
    {
        _effectMesh = GetComponent<EffectMesh>();
    }

    private void OnEnable()
    {
        _initRoutine = StartCoroutine(InitWhenReady());
    }

    private void OnDisable()
    {
        if (_initRoutine != null) StopCoroutine(_initRoutine);
        if (_rescanRoutine != null) StopCoroutine(_rescanRoutine);
        if (_deferredApplyRoutine != null) StopCoroutine(_deferredApplyRoutine);
        _initRoutine = _rescanRoutine = _deferredApplyRoutine = null;

        if (_mruk != null)
        {
            _mruk.SceneLoadedEvent.RemoveListener(HandleSceneLoaded);
            _mruk.RoomCreatedEvent.RemoveListener(HandleRoomChanged);
            _mruk.RoomUpdatedEvent.RemoveListener(HandleRoomChanged);
        }
    }

    private IEnumerator InitWhenReady()
    {
        while (MRUK.Instance == null)
        {
            yield return null;
        }

        _mruk = MRUK.Instance;

        if (applyOnSceneLoaded)
        {
            // Invoked immediately if the scene is already loaded, otherwise on scene load.
            _mruk.RegisterSceneLoadedCallback(HandleSceneLoaded);
        }

        if (reapplyOnRoomUpdated)
        {
            _mruk.RoomCreatedEvent.AddListener(HandleRoomChanged);
            _mruk.RoomUpdatedEvent.AddListener(HandleRoomChanged);
        }

        if (periodicRescanInterval > 0f && _rescanRoutine == null)
        {
            _rescanRoutine = StartCoroutine(RescanRoutine());
        }

        _initRoutine = null;
    }

    private void HandleSceneLoaded() => ScheduleApply();

    private void HandleRoomChanged(MRUKRoom room) => ScheduleApply();

    private IEnumerator RescanRoutine()
    {
        var wait = new WaitForSeconds(periodicRescanInterval);
        while (enabled)
        {
            ApplyToExisting();
            yield return wait;
        }
    }

    /// <summary>
    /// Defers the apply to the next frame: the EffectMesh generates/regenerates its objects
    /// within the same MRUK events, so we wait until it is done.
    /// </summary>
    private void ScheduleApply()
    {
        if (_deferredApplyRoutine != null) return;
        _deferredApplyRoutine = StartCoroutine(DeferredApply());
    }

    private IEnumerator DeferredApply()
    {
        yield return null;
        _deferredApplyRoutine = null;
        ApplyToExisting();
    }

    /// <summary>
    /// Iterates over all objects generated by the EffectMesh and applies the components to those
    /// that pass the filter. Idempotent: it can be called as many times as needed.
    /// </summary>
    /// <returns>Number of new objects hooked in this call.</returns>
    public int ApplyToExisting()
    {
        if (_effectMesh == null)
        {
            return 0;
        }

        CleanupDestroyed();

        int newlyMatched = 0;
        foreach (var kv in _effectMesh.EffectMeshObjects)
        {
            var anchor = kv.Key;
            var emo = kv.Value;
            if (anchor == null || emo?.effectMeshGO == null)
            {
                continue;
            }

            if (!PassesFilter(anchor.Label))
            {
                continue;
            }

            if (ApplyToObject(anchor, emo))
            {
                newlyMatched++;
            }
        }

        return newlyMatched;
    }

    private bool ApplyToObject(MRUKAnchor anchor, EffectMesh.EffectMeshObject emo)
    {
        var go = emo.effectMeshGO;
        bool isNew = !_managed.TryGetValue(anchor, out var known) || known != go;
        _managed[anchor] = go;

        if (addNavMeshObstacle)
        {
            ConfigureObstacle(go, anchor, emo);
        }

        if (isNew)
        {
            onEffectMeshMatched?.Invoke(go, anchor);
            if (logActions)
            {
                Debug.Log($"[EffectMeshComponentApplier] Hooked '{go.name}' (label: {anchor.Label}).", go);
            }
        }

        return isNew;
    }

    private void ConfigureObstacle(GameObject go, MRUKAnchor anchor, EffectMesh.EffectMeshObject emo)
    {
        if (!TryGetLocalBounds(go, anchor, emo, out var localBounds))
        {
            return;
        }

        var obstacle = go.GetComponent<NavMeshObstacle>();
        if (obstacle == null)
        {
            obstacle = go.AddComponent<NavMeshObstacle>();
        }

        obstacle.shape = shape;
        obstacle.carving = carving;
        obstacle.carveOnlyStationary = carveOnlyStationary;
        obstacle.carvingMoveThreshold = carvingMoveThreshold;
        obstacle.carvingTimeToStationary = carvingTimeToStationary;
        obstacle.center = localBounds.center;

        var size = MaxAbs(localBounds.size, minimumSize);

        if (shape == NavMeshObstacleShape.Box)
        {
            obstacle.size = size;
        }
        else
        {
            obstacle.radius = Mathf.Max(size.x, size.z) * 0.5f;
            obstacle.height = size.y;
        }
    }

    /// <summary>
    /// Resolves the local-space bounds of the effect mesh, trying in order: generated BoxCollider,
    /// anchor volume (tables/furniture), anchor plane (walls), mesh bounds.
    /// </summary>
    private bool TryGetLocalBounds(GameObject go, MRUKAnchor anchor, EffectMesh.EffectMeshObject emo, out Bounds bounds)
    {
        if (emo.collider is BoxCollider box)
        {
            bounds = new Bounds(box.center, box.size);
            return true;
        }

        if (anchor.VolumeBounds.HasValue)
        {
            bounds = anchor.VolumeBounds.Value;
            return true;
        }

        if (anchor.PlaneRect.HasValue)
        {
            var rect = anchor.PlaneRect.Value;
            bounds = new Bounds(
                new Vector3(rect.center.x, rect.center.y, 0f),
                new Vector3(rect.size.x, rect.size.y, planeThickness));
            return true;
        }

        if (emo.mesh != null)
        {
            bounds = emo.mesh.bounds;
            return true;
        }

        var meshFilter = go.GetComponent<MeshFilter>();
        if (meshFilter != null && meshFilter.sharedMesh != null)
        {
            bounds = meshFilter.sharedMesh.bounds;
            return true;
        }

        bounds = default;
        return false;
    }

    private bool PassesFilter(MRUKAnchor.SceneLabels label) => (targetLabels & label) != 0;

    private void CleanupDestroyed()
    {
        List<MRUKAnchor> toRemove = null;
        foreach (var kv in _managed)
        {
            if (kv.Key == null || kv.Value == null)
            {
                (toRemove ??= new List<MRUKAnchor>()).Add(kv.Key);
            }
        }

        if (toRemove == null)
        {
            return;
        }

        foreach (var key in toRemove)
        {
            _managed.Remove(key);
        }
    }

    private static Vector3 MaxAbs(Vector3 value, Vector3 minimum)
    {
        return new Vector3(
            Mathf.Max(Mathf.Abs(value.x), minimum.x),
            Mathf.Max(Mathf.Abs(value.y), minimum.y),
            Mathf.Max(Mathf.Abs(value.z), minimum.z));
    }

    // ---------------------------------------------------------------------
    //  Public API to act on the managed objects later on.
    // ---------------------------------------------------------------------

    /// <summary>Runs an action on every currently managed object.</summary>
    public void ForEachManaged(Action<GameObject, MRUKAnchor> action)
    {
        if (action == null)
        {
            return;
        }

        foreach (var kv in _managed)
        {
            if (kv.Key != null && kv.Value != null)
            {
                action(kv.Value, kv.Key);
            }
        }
    }

    /// <summary>Enables/disables carving on all managed obstacles.</summary>
    public void SetCarving(bool enabled)
    {
        carving = enabled;
        ForEachManaged((go, _) =>
        {
            if (go.TryGetComponent<NavMeshObstacle>(out var o))
            {
                o.carving = enabled;
            }
        });
    }

    /// <summary>Enables/disables the managed NavMeshObstacle components (without destroying them).</summary>
    public void SetObstaclesEnabled(bool enabled)
    {
        ForEachManaged((go, _) =>
        {
            if (go.TryGetComponent<NavMeshObstacle>(out var o))
            {
                o.enabled = enabled;
            }
        });
    }

    /// <summary>Removes all added NavMeshObstacle components and clears the registry.</summary>
    public void RemoveObstacles()
    {
        ForEachManaged((go, _) =>
        {
            if (go.TryGetComponent<NavMeshObstacle>(out var o))
            {
                Destroy(o);
            }
        });
        _managed.Clear();
    }
}
